**************************************************
NWBInspector Report Summary

Timestamp: 2022-08-21 17:34:58.585057+01:00
Platform: Linux-5.17.5-76051705-generic-x86_64-with-glibc2.35
NWBInspector version: 0.4.12

Found 6 issues over 1 files:
       2 - ERROR
       3 - CRITICAL
       1 - BEST_PRACTICE_VIOLATION
**************************************************


0  ERROR
========

0.0  /tmp/nwb_versions/sub-8675309_ses-20211008T163543_ophys.nwb: check_order_of_images_unique - 'None' object with name 'None'
       Message: Traceback (most recent call last):
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/nwbinspector/nwbinspector.py", line 554, in run_checks
    output = robust_s3_read(command=check_function, command_args=[nwbfile_object])
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/nwbinspector/utils.py", line 166, in robust_s3_read
    raise exc
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/nwbinspector/utils.py", line 161, in robust_s3_read
    return command(*command_args, **command_kwargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/nwbinspector/register_checks.py", line 128, in auto_parse_some_output
    output = check_function(*args, **kwargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/nwbinspector/checks/images.py", line 19, in check_order_of_images_unique
    if images.order_of_images is None:
AttributeError: 'Images' object has no attribute 'order_of_images'


0.1  /tmp/nwb_versions/sub-8675309_ses-20211008T163543_ophys.nwb: check_order_of_images_len - 'None' object with name 'None'
       Message: Traceback (most recent call last):
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/nwbinspector/nwbinspector.py", line 554, in run_checks
    output = robust_s3_read(command=check_function, command_args=[nwbfile_object])
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/nwbinspector/utils.py", line 166, in robust_s3_read
    raise exc
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/nwbinspector/utils.py", line 161, in robust_s3_read
    return command(*command_args, **command_kwargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/nwbinspector/register_checks.py", line 128, in auto_parse_some_output
    output = check_function(*args, **kwargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/nwbinspector/checks/images.py", line 26, in check_order_of_images_len
    if images.order_of_images is None:
AttributeError: 'Images' object has no attribute 'order_of_images'


1  CRITICAL
===========

1.2  /tmp/nwb_versions/sub-8675309_ses-20211008T163543_ophys.nwb: check_roi_response_series_dims - 'RoiResponseSeries' object at location '/processing/ophys/Neuropil/Neuropil'
       Message: The second dimension of data does not match the length of rois, but instead the first does. Data is oriented incorrectly and should be transposed.

1.3  /tmp/nwb_versions/sub-8675309_ses-20211008T163543_ophys.nwb: check_roi_response_series_dims - 'RoiResponseSeries' object at location '/processing/ophys/Fluorescence/Fluorescence'
       Message: The second dimension of data does not match the length of rois, but instead the first does. Data is oriented incorrectly and should be transposed.

1.4  /tmp/nwb_versions/sub-8675309_ses-20211008T163543_ophys.nwb: check_roi_response_series_dims - 'RoiResponseSeries' object at location '/processing/ophys/Deconvolved/Deconvolved'
       Message: The second dimension of data does not match the length of rois, but instead the first does. Data is oriented incorrectly and should be transposed.

2  BEST_PRACTICE_VIOLATION
==========================

2.5  /tmp/nwb_versions/sub-8675309_ses-20211008T163543_ophys.nwb: check_subject_species_exists - 'Subject' object at location '/general/subject'
       Message: Subject species is missing.

