**************************************************
NWBInspector Report Summary

Timestamp: 2022-08-21 18:03:39.873818+01:00
Platform: Linux-5.17.5-76051705-generic-x86_64-with-glibc2.35
NWBInspector version: 0.4.12

Found 1 issues over 1 files:
       1 - ERROR
**************************************************


0  ERROR
========

0.0  /tmp/nwb_versions/sub-112_ses-Ca-VS-VR-4.nwb: During io.read() - <class 'hdmf.build.errors.ConstructError'>: (root/general/fiber_photometry/commanded_voltages GroupBuilder {'attributes': {'namespace': 'ndx-photometry', 'neurodata_type': 'MultiCommandedVoltage', 'object_id': 'c4b46ddf-c04b-47d6-a6c9-4210341bbafc'}, 'groups': {}, 'datasets': {}, 'links': {}}, "Could not construct MultiCommandedVoltage object due to: MultiContainerInterface.__make_add.<locals>._func: None is not allowed for 'commanded_voltage_series' (expected 'list, tuple, dict or CommandedVoltageSeries', not None)") - 'None' object with name 'None'
       Message: Traceback (most recent call last):
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 1248, in construct
    obj = self.__new_container__(cls, builder.source, parent, builder.attributes.get(self.__spec.id_key()),
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 1261, in __new_container__
    obj.__init__(**kwargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/utils.py", line 639, in func_call
    return func(args[0], **pargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/classgenerator.py", line 403, in __init__
    add_method(new_kwarg['value'])
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/utils.py", line 638, in func_call
    pargs = _check_args(args, kwargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/utils.py", line 631, in _check_args
    raise ExceptionType(msg)
TypeError: MultiContainerInterface.__make_add.<locals>._func: None is not allowed for 'commanded_voltage_series' (expected 'list, tuple, dict or CommandedVoltageSeries', not None)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/nwbinspector/nwbinspector.py", line 528, in inspect_nwb
    nwbfile = robust_s3_read(command=io.read, max_retries=max_retries)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/nwbinspector/utils.py", line 166, in robust_s3_read
    raise exc
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/nwbinspector/utils.py", line 161, in robust_s3_read
    return command(*command_args, **command_kwargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/backends/hdf5/h5tools.py", line 451, in read
    return super().read(**kwargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/utils.py", line 639, in func_call
    return func(args[0], **pargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/backends/io.py", line 42, in read
    container = self.__manager.construct(f_builder)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/utils.py", line 639, in func_call
    return func(args[0], **pargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/manager.py", line 280, in construct
    result = self.__type_map.construct(builder, self, None)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/utils.py", line 639, in func_call
    return func(args[0], **pargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/manager.py", line 789, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/utils.py", line 639, in func_call
    return func(args[0], **pargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 1218, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 1147, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 1198, in __get_sub_builders
    ret.update(self.__get_subspec_values(sub_builder, subspec, manager))
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 1147, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 1190, in __get_sub_builders
    sub_builder = self.__flatten(sub_builder, subspec, manager)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 1203, in __flatten
    tmp = [manager.construct(b) for b in sub_builder]
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 1203, in <listcomp>
    tmp = [manager.construct(b) for b in sub_builder]
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/utils.py", line 639, in func_call
    return func(args[0], **pargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/manager.py", line 276, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/utils.py", line 639, in func_call
    return func(args[0], **pargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/manager.py", line 789, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/utils.py", line 639, in func_call
    return func(args[0], **pargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 1218, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 1147, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 1200, in __get_sub_builders
    ret[subspec] = manager.construct(sub_builder)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/utils.py", line 639, in func_call
    return func(args[0], **pargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/manager.py", line 276, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/utils.py", line 639, in func_call
    return func(args[0], **pargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/manager.py", line 789, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/utils.py", line 639, in func_call
    return func(args[0], **pargs)
  File "/home/anh/anaconda3/envs/test_envDANDI/lib/python3.9/site-packages/hdmf/build/objectmapper.py", line 1252, in construct
    raise ConstructError(builder, msg) from ex
hdmf.build.errors.ConstructError: (root/general/fiber_photometry/commanded_voltages GroupBuilder {'attributes': {'namespace': 'ndx-photometry', 'neurodata_type': 'MultiCommandedVoltage', 'object_id': 'c4b46ddf-c04b-47d6-a6c9-4210341bbafc'}, 'groups': {}, 'datasets': {}, 'links': {}}, "Could not construct MultiCommandedVoltage object due to: MultiContainerInterface.__make_add.<locals>._func: None is not allowed for 'commanded_voltage_series' (expected 'list, tuple, dict or CommandedVoltageSeries', not None)")


